version: '3'
services:
  notebook:
    build: .
    env_file: .env
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/notebooks/local_notebooks
      - /tmp:/tmp
      - /mnt/scratch07:/external
      - /mnt/lab/microns/data:/data
      - ./:/src/static-networks
    network_mode: "host"
    entrypoint:
      - jupyter 
      - lab
      - --ip=0.0.0.0
      - --allow-root
      - --NotebookApp.token=$JUPYTER_PASSWORD
      - --no-browser

  bash:
    build: .
    env_file: .env
    ports:
      - "8888:8888"
    volumes:
      - ./:/src/static-networks
      - /tmp:/tmp
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/scratch07:/external
    working_dir: /scripts